# ============================
# Kafka base
# ============================
kafka.bootstrap.servers=localhost:9092
kafka.group.id=saga-orchestrator
kafka.auto.offset.reset=earliest
kafka.enable.auto.commit=true

kafka.dlq.topic=_orchestrator.dlq
kafka.retry.topic=_orchestrator.retry
kafka.state.topic=_orchestrator.state

# ============================
# Convenções globais
# ============================
# Identificar tipo do evento
# - payload: pega o campo definido por event.type.path (formato $.a.b)
# - topic: usa o nome do tópico como tipo (topic name)

event.type.source=payload
event.type.path=$.type

# Correlation (Saga ID)
correlation.source=payload
correlation.path=$.correlationId

# Timeouts (ms)
saga.step.timeout.ms=30000

# ============================
# Catálogo de eventos de entrada
# ============================
# Formato:
# event.in.<EventName>.topic=<topic>
# event.in.<EventName>.type=<EventName>   (usado quando event.type.source=topic)

event.in.OrderCreated.topic=orders.created

event.in.PaymentReserved.topic=payments.reserved

event.in.InventoryConfirmed.topic=inventory.confirmed

event.in.InventoryFailed.topic=inventory.failed

# ============================
# Catálogo de comandos de saída
# ============================
command.out.ReservePayment.topic=payments.reserve
command.out.ConfirmInventory.topic=inventory.confirm
command.out.RollbackPayment.topic=payments.rollback

command.out.SagaCompleted.topic=saga.completed
command.out.SagaFailed.topic=saga.failed

# ============================
# Regras de roteamento simples (v1)
# ============================
# route.<IncomingEventType>.emit=Cmd1,Cmd2

route.OrderCreated.emit=ReservePayment,ConfirmInventory
route.InventoryFailed.emit=RollbackPayment
route.InventoryConfirmed.emit=SagaCompleted

# ============================
# Política de erro
# ============================
# error.on.parse=DLQ
#error.on.missing.correlation=DLQ
#error.on.unknown.event=IGNORE
#error.on.publish.fail=RETRY
