spring.application.name=nfe-cache
nfe.cache.redis.enabled=true
nfe.cache.redis.key-prefix=nfe
nfe.cache.redis.namespace=producao
nfe.cache.redis.verbose-logging=false
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=nfe-cache-group
nfe.cache.enabled=true
nfe.cache.key-prefix=nfe
nfe.cache.ttl=24h
nfe.kafka.topic=nfe-recebidas