spring.application.name=rediscache
teste.cache.redis.enabled=true
teste.cache.redis.key-prefix=rediscache
teste.cache.redis.namespace=producao
teste.cache.redis.verbose-logging=false
teste.cache.redis.ttl=1800s